#!/bin/sh

IFACE="$1"
ACTION="$2"

if [ "$IFACE" = "eth0" ] && { [ "$ACTION" = "up" ] || [ "$ACTION" = "dhcp4-change" ] || [ "$ACTION" = "connectivity-change" ]; }; then
  /usr/sbin/ip addr show dev eth0 | /bin/grep -q '192.168.144.101/32' || /usr/sbin/ip addr add 192.168.144.101/32 dev eth0
  /usr/sbin/ip route replace 192.168.144.108/32 dev eth0 src 192.168.144.101
fi
